spring.application.name=exam-service
server.port= 8084
eureka.client.service-url.defaultZone= http://localhost:8761/eureka
eureka.register-with-eureka= true
eureka.fetch-registry= true
eureka.instance.prefer-ip-address= true
spring.datasource.url=jdbc:h2:mem:exams-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
